baseurl = "http://thinkhike.com/"
languageCode = "en-us"
title = "Think Hike"
theme = "hugo-uno"

[params]
  description = "Let's hike together to learn, grow, and have fun!"
  author = "Nikola Tesla"